language: ruby
before_install:
  - sudo apt-get install libxml2-dev libxslt1-dev
  - gem update --system
  - gem install bundler -v "~> 2.0"
rvm:
  - 2.5
  - 2.6
  - 2.7
  - jruby
  - rbx
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx
script: rake test
